# Generated by Django 5.0 on 2023-12-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined_donorprofiler'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonorProfiler',
            new_name='DonorProfile',
        ),
    ]
