# Generated by Django 5.0 on 2024-01-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_donorprofiler_donorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='rh_factor',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10, null=True),
        ),
    ]
